# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreateurBranchement
                                 A QGIS plugin
 Ce plugin crée des branchements à partir d'un jeu de données de vannes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-08
        copyright            : (C) 2022 by Runéo
        email                : omranedoo@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreateurBranchement class from file CreateurBranchement.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .createur_branchement import CreateurBranchement
    return CreateurBranchement(iface)
